/*
 * Project: Dougs Donuts
 * This: frompos.java
 * Date: 12/7/14
 * Author: Chad Nordstrom
 * Purpose: To calcualte the total price of a visit to a donut shop.
 */
package dougsdonuts;

/**
 *
 * @author CN276
 */
import java.text.NumberFormat;
import javax.swing.JOptionPane;

public class frmPOS extends javax.swing.JFrame {
    protected static final double DONUT_PRICE = 1.09f;
    protected static final double COFFEE_PRICE = 1.29f;
    protected static final String DPRICE = "$1.09";
    protected static final String CPRICE = "$1.29";
    /**
     * Creates new form frmPOS
     */
    public frmPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotal = new javax.swing.JLabel();
        lblDonuts1 = new javax.swing.JLabel();
        lblCoffee1 = new javax.swing.JLabel();
        lblNet1 = new javax.swing.JLabel();
        lblStateTax1 = new javax.swing.JLabel();
        lblLocalTax1 = new javax.swing.JLabel();
        txtDonuts = new javax.swing.JTextField();
        txtCoffees = new javax.swing.JTextField();
        lblTotalVal = new javax.swing.JLabel();
        lblDonutPrice = new javax.swing.JLabel();
        lblCoffeePrice = new javax.swing.JLabel();
        lblDonutSub = new javax.swing.JLabel();
        lblCoffeeSub = new javax.swing.JLabel();
        lblNetVal = new javax.swing.JLabel();
        lblStateTaxVal = new javax.swing.JLabel();
        lblLocalTaxVal = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnCalculate1 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Doug's Donuts");
        setBackground(new java.awt.Color(255, 255, 0));
        setMinimumSize(new java.awt.Dimension(445, 354));
        setName("frmPOS"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setText("Total Sale: ");
        lblTotal.setName("frmPOS"); // NOI18N
        getContentPane().add(lblTotal);
        lblTotal.setBounds(280, 230, 80, 20);

        lblDonuts1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDonuts1.setText("Donuts: ");
        lblDonuts1.setName("frmPOS"); // NOI18N
        getContentPane().add(lblDonuts1);
        lblDonuts1.setBounds(40, 40, 70, 20);

        lblCoffee1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCoffee1.setText("Coffees:");
        lblCoffee1.setName("frmPOS"); // NOI18N
        getContentPane().add(lblCoffee1);
        lblCoffee1.setBounds(40, 80, 70, 20);

        lblNet1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNet1.setText("Net Sale:");
        lblNet1.setName("frmPOS"); // NOI18N
        getContentPane().add(lblNet1);
        lblNet1.setBounds(290, 140, 70, 20);

        lblStateTax1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStateTax1.setText("State Tax: ");
        lblStateTax1.setName("frmPOS"); // NOI18N
        getContentPane().add(lblStateTax1);
        lblStateTax1.setBounds(280, 170, 80, 20);

        lblLocalTax1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLocalTax1.setText("Local Tax:");
        lblLocalTax1.setName("frmPOS"); // NOI18N
        getContentPane().add(lblLocalTax1);
        lblLocalTax1.setBounds(280, 200, 80, 20);

        txtDonuts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDonuts.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtDonuts);
        txtDonuts.setBounds(120, 40, 50, 23);

        txtCoffees.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCoffees.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtCoffees);
        txtCoffees.setBounds(120, 80, 50, 23);

        lblTotalVal.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalVal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTotalVal.setOpaque(true);
        getContentPane().add(lblTotalVal);
        lblTotalVal.setBounds(370, 230, 60, 20);

        lblDonutPrice.setBackground(new java.awt.Color(255, 255, 255));
        lblDonutPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDonutPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDonutPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDonutPrice.setOpaque(true);
        getContentPane().add(lblDonutPrice);
        lblDonutPrice.setBounds(190, 40, 60, 20);

        lblCoffeePrice.setBackground(new java.awt.Color(255, 255, 255));
        lblCoffeePrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCoffeePrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCoffeePrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCoffeePrice.setOpaque(true);
        getContentPane().add(lblCoffeePrice);
        lblCoffeePrice.setBounds(190, 80, 60, 20);

        lblDonutSub.setBackground(new java.awt.Color(255, 255, 255));
        lblDonutSub.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDonutSub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDonutSub.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblDonutSub.setOpaque(true);
        getContentPane().add(lblDonutSub);
        lblDonutSub.setBounds(370, 40, 60, 20);

        lblCoffeeSub.setBackground(new java.awt.Color(255, 255, 255));
        lblCoffeeSub.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCoffeeSub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCoffeeSub.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCoffeeSub.setOpaque(true);
        getContentPane().add(lblCoffeeSub);
        lblCoffeeSub.setBounds(370, 80, 60, 20);

        lblNetVal.setBackground(new java.awt.Color(255, 255, 255));
        lblNetVal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNetVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNetVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblNetVal.setOpaque(true);
        getContentPane().add(lblNetVal);
        lblNetVal.setBounds(370, 140, 60, 20);

        lblStateTaxVal.setBackground(new java.awt.Color(255, 255, 255));
        lblStateTaxVal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStateTaxVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStateTaxVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblStateTaxVal.setOpaque(true);
        getContentPane().add(lblStateTaxVal);
        lblStateTaxVal.setBounds(370, 170, 60, 20);

        lblLocalTaxVal.setBackground(new java.awt.Color(255, 255, 255));
        lblLocalTaxVal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLocalTaxVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLocalTaxVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblLocalTaxVal.setOpaque(true);
        getContentPane().add(lblLocalTaxVal);
        lblLocalTaxVal.setBounds(370, 200, 60, 20);

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(310, 280, 120, 40);

        btnCalculate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCalculate1.setText("Calculate");
        btnCalculate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculate1);
        btnCalculate1.setBounds(50, 280, 110, 40);

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(180, 280, 110, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Are you sure?", "Quit?", 
                JOptionPane.YES_NO_OPTION);
        
        if(result == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        lblDonutPrice.setText(DPRICE);
        lblCoffeePrice.setText(CPRICE);
        txtDonuts.setText("0");
        txtCoffees.setText("0");
    }//GEN-LAST:event_formWindowActivated

    private void btnCalculate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate1ActionPerformed
        // TODO add your handling code here:
        final double LOCAL_TAX = .02;
        final double STATE_TAX = .065;
        
        NumberFormat nf = NumberFormat.getCurrencyInstance();
        
        int intDonuts = Integer.parseInt(txtDonuts.getText());
        int intCoffees = Integer.parseInt(txtCoffees.getText());
        
        double dblDonutsSub = intDonuts * DONUT_PRICE;
        double dblCoffeesSub = intCoffees * COFFEE_PRICE;
        
        lblDonutSub.setText(nf.format(dblDonutsSub));
        lblCoffeeSub.setText(nf.format(dblCoffeesSub));
        
        double dblNetSale = dblDonutsSub + dblCoffeesSub;
        lblNetVal.setText(nf.format(dblNetSale));
        
        double dblStateTax = dblNetSale * STATE_TAX;
        double dblLocalTax = dblNetSale * LOCAL_TAX;
        lblStateTaxVal.setText(nf.format(dblStateTax));
        lblLocalTaxVal.setText(nf.format(dblLocalTax));
        
        double dblTotal = dblNetSale + dblStateTax + dblLocalTax;
        lblTotalVal.setText(nf.format(dblTotal));
        
        btnClear.requestFocusInWindow();
        
        
        
        
        
        
    }//GEN-LAST:event_btnCalculate1ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        lblDonutSub.setText("");
        lblCoffeeSub.setText("");
        lblNetVal.setText("");
        lblStateTaxVal.setText("");
        lblLocalTaxVal.setText("");
        lblTotalVal.setText("");
        txtDonuts.setText("0");
        txtCoffees.setText("0");
        
        txtDonuts.requestFocusInWindow();
    }//GEN-LAST:event_btnClearActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Are you sure?", "Quit?", 
                JOptionPane.YES_NO_OPTION);
        
        if(result == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPOS().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate1;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel lblCoffee1;
    private javax.swing.JLabel lblCoffeePrice;
    private javax.swing.JLabel lblCoffeeSub;
    private javax.swing.JLabel lblDonutPrice;
    private javax.swing.JLabel lblDonutSub;
    private javax.swing.JLabel lblDonuts1;
    private javax.swing.JLabel lblLocalTax1;
    private javax.swing.JLabel lblLocalTaxVal;
    private javax.swing.JLabel lblNet1;
    private javax.swing.JLabel lblNetVal;
    private javax.swing.JLabel lblStateTax1;
    private javax.swing.JLabel lblStateTaxVal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalVal;
    private javax.swing.JTextField txtCoffees;
    private javax.swing.JTextField txtDonuts;
    // End of variables declaration//GEN-END:variables
}
